[package]
name = "bn254-example"
version = "0.1.0"
edition = "2021"

default-run = "bn254-example"

[dependencies]
bn254-core = { path = "core" }
bn254-methods = { path = "methods" }
substrate-bn = "0.6.0"
hex = "0.4.3"
risc0-zkvm = { path = "../../risc0/zkvm" }

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
prove = ["risc0-zkvm/prove"]

[patch.crates-io]
# TODO: Get a tag stabilized and use it
substrate-bn = { git = "https://github.com/risc0/paritytech-bn", rev = "5bc9b486320e64a20a967568b5e9c0e6aee0307b" }
