[package]
name = "bn254-example"
version = "0.1.0"
edition = "2021"

default-run = "bn254-example"  # TODO?

[dependencies]
bn254-core = { path = "core" }
bn254-methods = { path = "methods" }
substrate-bn = "0.6.0"
hex = "0.4.3"
risc0-zkvm = { path = "../../risc0/zkvm" }

# [features]
# TODO
# cuda = ["risc0-zkvm/cuda"]
# default = []
# prove = ["risc0-zkvm/prove"]
