[package]
name = "hello-world-methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { path = "../../../risc0/build" }
util = { path = "../../util/", optional = true }

[package.metadata.risc0]
methods = ["guest"]

[features]
client = ["dep:util"]
default = ["client"]
prove = ["dep:util", "util/prove"]
