[package]
name = "voting-machine-methods"
version = "0.12.0"
edition = "2021"

[package.metadata.risc0]
methods = ["guest"]

[build-dependencies]
util = { path = "../../util" }

[features]
prove = ["util/prove"]
