[package]
name = "prover-example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bytemuck = "1.20.0"
num-bigint = { version = "0.4", features = ["serde"] }
risc0-circuit-keccak = { path = "../../risc0/circuit/keccak/" }
risc0-circuit-keccak-methods = { path = "../../risc0/circuit/keccak/methods" }
risc0-zkp = { path = "../../risc0/zkp" }
risc0-zkvm = { path = "../../risc0/zkvm", features = ["unstable"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
workerpool = "1.2"

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
