[package]
name = "smartcore-ml-methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
util = { path = "../../util" }

[package.metadata.risc0]
methods = ["guest"]

[features]
prove = ["util/prove"]
