[workspace]
resolver = "2"
members = ["rest-api-mock", "sdk"]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[workspace.dependencies]
bonsai-rest-api-mock = { version = "0.8.0-alpha.1", default-features = false, path = "rest-api-mock" }
bonsai-sdk = { version = "0.8.0-alpha.1", default-features = false, path = "sdk" }
risc0-build = { version = "0.22.0-alpha.1", default-features = false, path = "../risc0/build" }
risc0-groth16 = { version = "0.22.0-alpha.1", default-features = false, path = "../risc0/groth16" }
risc0-zkvm = { version = "0.22.0-alpha.1", default-features = false, path = "../risc0/zkvm" }

[profile.bench]
lto = true

# Always optimize; otherwise tests take excessively long.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
