[package]
name = "redis-executor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
risc0-zkvm = { path = "../../risc0/zkvm" }
sample-guest-methods = { path = "./methods" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
redis = ["risc0-zkvm/redis"]
prove = ["risc0-zkvm/prove"]
