[package]
name = "prover"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
bincode = "1.3"
risc0-zkvm = { workspace = true, features = ["prove"] }
risc0-zkvm-methods = { path = "../../risc0/zkvm/methods" }
workerpool = "1.2"
