[package]
name = "risc0-zkos-v1compat"
version = "0.1.0"
edition = { workspace = true }

[[bin]]
name = "v1compat"
path = "src/main.rs"

[dependencies]
no_std_strings = "0.1.3"

[build-dependencies]
risc0-build = { workspace = true }

[package.metadata.release]
release = false

[package.metadata.risc0]
kernel = true
