[package]
name = "risc0-circuit-bigint-test-dig-methods"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
num-bigint = { version = "0.8.2", default-features = false, features = ["serde"], package = "num-bigint-dig" }
risc0-circuit-bigint = { path = "../..", default-features = false, features = ["bigint-dig-shim"] }
risc0-zkvm = { path = "../../../../zkvm", default-features = false, features = [
    "std",
    "unstable",
] }
risc0-zkvm-platform = { path = "../../../../zkvm/platform", default-features = false, features = ["sys-getenv"] }
