[package]
name = "rzup"
description = "The RISC Zero version management library and CLI"
version = "0.3.0-alpha.1"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[package.metadata.release]
release = false

[[bin]]
name = "rzup"
path = "src/bin/rzup.rs"
required-features = ["cli"] # check this

[features]
default = ["cli"] # and this
cli = ["dep:clap", "dep:indicatif", "dep:colored"]

[dependencies]
anyhow = { version = "1.0.94", features = ["backtrace"] }
thiserror = "2.0.7"
dirs = "5.0.1"
tempfile = "3.14.0"
semver = "1.0.24"
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"
flate2 = "1.0.35"
fs2 = "0.4.3"
xz = "0.1.0"
tar = "0.4.43"
reqwest = { version = "0.12.9", default-features = false, features = ["rustls-tls", "blocking", "json"] }

# cli dependencies
clap = { version = "4.5.23", features = ["derive"], optional = true }
indicatif = { version = "0.17.9", optional = true }
colored = { version = "2.2.0", optional = true }
enumset = "1.1.5"
strum = { version = "0.26.3", features = ["derive"] }

[dev-dependencies]
http-body-util = "0.1.2"
hyper = { version = "1.5.1", features = ["server"] }
hyper-util = "0.1.10"
maplit = "1.0.2"
paste = "1.0.15"
tokio = { version = "1.42.0", features = ["rt", "rt-multi-thread", "macros"] }
