[package]
name = "rzup"
description = "utility to install the RISC Zero toolchain"
version = "0.2.2"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[package.metadata.release]
release = false

[dependencies]
anyhow = "1.0.93"
cfg-if = "1.0.0"
clap = { version = "4.5.22", features = ["derive"] }
dirs = "5.0.1"
downloader = "0.2.8"
flate2 = "1.0.34"
fs2 = "0.4.3"
lazy_static = "1.5.0"
regex = "1.11.1"
reqwest = { version = "0.12", default-features = false, features = [
  "json",
  "rustls-tls",
] }
risc0-build = { path = "../risc0/build" }
serde = { version = "1.0.215", features = ["derive"] }
tar = "0.4.43"
tempfile = "3.12.0"
termcolor = "1.4.1"
thiserror = "1.0.65"
tokio = { version = "1.42.0", features = ["rt-multi-thread", "macros"] }
xz = "0.1.0"
