[package]
name = "risc0-build-kernel"
description = "RISC Zero tool for building kernels"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
directories = "5.0"
glob = "0.3"
hex = "0.4"
rayon = "1.10"
sha2 = "0.10"
tempfile = "3.12"

[dependencies.cc]
git = "https://github.com/rust-lang/cc-rs.git"
rev = "4f312e3f3b2b4623e84518582a3ff17bbae70906"
features = ["parallel"]
