name: Benchmark Datasheet

on:
  push:
    branches: [ main ]
    # Only run benchmarks on changes to following paths:
    paths:
      - 'risc0/**'
      - '.github/workflows/bench_datasheet.yml'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# this is needed to gain access via OIDC to the S3 bucket for caching
permissions:
  id-token: write
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RISC0_BUILD_LOCKED: 1
  RISC0_TOOLCHAIN_VERSION: v2024-04-22.0

defaults:
  run:
    # This ensures `-eo pipefail`, which is important for catching errors
    shell: bash

jobs:
  bench:
    runs-on: [self-hosted, prod, bench, "${{ matrix.os }}", "${{ matrix.device }}"]

    strategy:
      fail-fast: false
      matrix:
        os: [Linux, macOS]
        feature: [prove]
        device: [cpu]
        include:
          - os: Linux
            feature: cuda
            device: nvidia_rtx_3090_ti
          - os: macOS
            feature: metal
            device: apple_m2_pro

    env:
      FEATURE: ${{ matrix.feature }}

    steps:
      # This is a workaround from: https://github.com/actions/checkout/issues/590#issuecomment-970586842
      - run: "git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :"
      - uses: actions/checkout@v4
      - if: matrix.feature == 'cuda'
        uses: ./.github/actions/cuda
      - uses: ./.github/actions/rustup
      - uses: ./.github/actions/sccache
        with:
          key: ${{ matrix.os }}-${{ matrix.feature }}
      - run: cargo run --bin cargo-risczero --no-default-features -- risczero install --version $RISC0_TOOLCHAIN_VERSION
      - run: cargo run --release -F $FEATURE --example loop -- --json | tee ${{ matrix.os }}-${{ matrix.device }}.json
        working-directory: risc0/zkvm
      - name: Save commit hash to a file
        run: echo "${{ github.sha }}" > COMMIT_HASH.txt
        working-directory: risc0/zkvm
      - name: Upload benchmark result
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-result
          path: |
            risc0/zkvm/${{ matrix.os }}-${{ matrix.device }}.json
            risc0/zkvm/COMMIT_HASH.txt

  publish:
    needs: bench
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages repository
        uses: actions/checkout@v4
        with:
          repository: risc0/ghpages
          token: ${{ secrets.BENCHMARK_TOKEN }}
      - name: Download benchmark
        uses: actions/download-artifact@v2
        with:
          name: benchmark-result
          path: dev/datasheet
      - name: Push benchmark result
        run: |
          git config user.name "r0-ghbot"
          git config user.email "r0-ghbot@users.noreply.github.com"
          git add --all
          if git diff --cached --exit-code; then
            echo "No changes to commit"
          else
            git commit -m "Add build artifacts"
            git push
          fi
