name: bonsai

on:
  merge_group:
  pull_request:
    branches: [main, "release-*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# this is needed to gain access via OIDC to the S3 bucket for caching
permissions:
  id-token: write
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RISC0_BUILD_LOCKED: 1
  RISC0_TOOLCHAIN_VERSION: v2024-04-22.0

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      bonsai: ${{ steps.filter.outputs.bonsai }}
    steps:
      - uses: actions/checkout@v4
      - uses: risc0/paths-filter@4067d885736b84de7c414f582ac45897079b0a78
        id: filter
        with:
          filters: |
            bonsai:
              - .github/actions/**
              - .github/workflows/bonsai.yml
              - bonsai/**
              - risc0/**
              - rust-toolchain.toml

  bonsai:
    if: needs.changes.outputs.bonsai == 'true'
    needs: changes
    runs-on: [self-hosted, prod, Linux, cpu]
    steps:
      # This is a workaround from: https://github.com/actions/checkout/issues/590#issuecomment-970586842
      - name: checkout dummy commit (submodule bug workaround)
        run: "git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :"

      - name: checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      # Install dependencies.
      - uses: ./.github/actions/rustup
      - uses: ./.github/actions/sccache
        with:
          key: Linux-default

      - name: Cargo install cargo-risczero
        run: cargo install --force --path risc0/cargo-risczero

      - run: cargo risczero install --version $RISC0_TOOLCHAIN_VERSION

      # Test
      - name: run cargo tests in bonsai
        run: cargo test --locked -- --include-ignored --nocapture
        working-directory: bonsai

      - run: sccache --show-stats
