name: website-test

on:
  merge_group:
  pull_request:
    branches: [main, "release-*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# this is needed to gain access via OIDC to the S3 bucket for caching
permissions:
  id-token: write
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RISC0_TOOLCHAIN_VERSION: v2024-04-22.0

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      main: ${{ steps.filter.outputs.main }}
      version-0_20: ${{ steps.filter.outputs.version-0_20 }}
    steps:
      - uses: actions/checkout@v4
      - uses: risc0/paths-filter@4067d885736b84de7c414f582ac45897079b0a78
        id: filter
        with:
          filters: |
            main:
              - rust-toolchain.toml
              - .github/actions/**
              - .github/workflows/website-test.yml
              - bonsai/**
              - risc0/**
              - website/api/**
              - website/doc-test/main/**
              - website/docs/**
            version-0_20:
              - .github/actions/**
              - .github/workflows/website-test.yml
              - website/api_versioned_docs/version-0.20/**
              - website/doc-test/version-0.20/**

  # see: https://github.com/orgs/community/discussions/26822
  doc-test:
    if: always()
    needs:
      - main
      - version-0_20
    runs-on: ubuntu-latest
    steps:
      - name: Check all job status
        # see https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#needs-context
        # see https://stackoverflow.com/a/67532120/4907315
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1

  main:
    if: needs.changes.outputs.main == 'true'
    needs: changes
    runs-on: [self-hosted, prod, Linux, cpu]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rustup
      - uses: ./.github/actions/sccache
        with:
          key: Linux-default
      - run: cargo run --bin cargo-risczero -- risczero install --version $RISC0_TOOLCHAIN_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        run: cargo test --release --no-run
        working-directory: website/doc-test/main
      - name: test
        run: cargo test --release
        working-directory: website/doc-test/main

      - run: sccache --show-stats

  version-0_20:
    if: needs.changes.outputs.version-0_20 == 'true'
    needs: changes
    runs-on: [self-hosted, prod, Linux, cpu]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rustup
      - uses: ./.github/actions/sccache
        with:
          key: Linux-default
      - uses: risc0/foundry-toolchain@2fe7e70b520f62368a0e3c464f997df07ede420f
        with:
          version: nightly-09fe3e041369a816365a020f715ad6f94dbce9f2
      - uses: risc0/cargo-install@b9307573043522ab0d3e3be64a51763b765b52a4
        with:
          crate: cargo-binstall
          version: "1.4"
      - run: cargo binstall -y --force cargo-risczero@0.20
      - run: cargo risczero install --version $RISC0_TOOLCHAIN_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        run: cargo test --release --no-run
        working-directory: website/doc-test/version-0.20
      - name: test
        run: cargo test --release
        working-directory: website/doc-test/version-0.20

      - run: sccache --show-stats
